### PR TITLE
don't self-close void elements

### PR DESCRIPTION
**Pull request by MartinNowak**
- self-closing void elements are an xhtrml thing
- still preserve them as HTML5 (and most HTML4 parsers) are
  compatible and some people might prefer <br />

### CODE REVIEW

**Comment by MartinNowak** [comment]
I'm a bit unsure about preserving the input. It might be better to always produce "correct" output regardless of the input.

**Comment by devebookingservices** [comment]
Yes, I think the way to go is to have the parser be tolerant and eat anything it can understand, but then produce compliant markup of what it parsed.

**Comment by MartinNowak** [comment]
> but then produce compliant markup of what it parsed.

Wait, then we should always output `<br>` no matter whether the input was `<br>` or `<br />`. Will make fixup.

**Comment by MartinNowak** [comment]
See #9

**Pull request merged**
